config/routes.rb
Rails.application.routes.draw do

  resources :products, only: :index do
    resources :orders, only: :create
  end

  resources :orders, only: :index do
  	collection do
  		get 'clean'
  	end
  end

  resources :billings, only: [:index] do
    collection do
      get 'pre_pay'
      get 'execute'
    end
  end

  devise_for :users

  root 'products#index'
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/billing.rb
class Billing < ApplicationRecord
  belongs_to :user
  has_many :orders
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  belongs_to :product

  belongs_to :billing, optional: true

  scope :cart, -> { where(payed: false) }

  def self.get_total
    pluck("price * quantity").sum()
  end
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :orders
  has_many :users, through: :orders
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :orders
  has_many :products, through: :orders
  has_many :billings
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :email, :password])
  end
end

app/controllers/billings_controller.rb
class BillingsController < ApplicationController
  before_action :authenticate_user!

  def index
    @billings = current_user.billings
  end

  def pre_pay
    orders = current_user.orders.cart
    total = orders.get_total
    items = get_items_hash(orders)

    # Build Payment object
    @payment = PayPal::SDK::REST::Payment.new({
      :intent =>  "sale",
      :payer =>  {
        :payment_method =>  "paypal" },
      :redirect_urls => {
        :return_url => execute_billings_url,
        :cancel_url => "http://localhost:3000/" },
      :transactions =>  [{
        :item_list => {
          :items => items
        },
        :amount =>  {
          :total =>  total,
          :currency =>  "USD" },
        :description =>  "Carro de compra" }]
    })

    if @payment.create
      redirect_url = @payment.links.find{|v| v.method == "REDIRECT" }.href
      redirect_to redirect_url
    else
      render json: @payment.error  # Error Hash
    end
  end

  def execute
    # render json:params
    paypal_payment = PayPal::SDK::REST::Payment.find(params[:paymentId])

    if paypal_payment.execute(payer_id: params[:PayerID])
      amount = paypal_payment.transactions.first.amount.total

      billing = Billing.create(
        user: current_user,
        code: paypal_payment.id,
        payment_method: 'paypal',
        amount: amount,
        currency: 'USD'
      )
     
      orders = current_user.orders.where(payed: false)
      orders.update_all(payed: true, billing_id: billing.id)
     
      redirect_to root_path, notice: "La compra se realizó con éxito!"
    else
      render plain: "No se puedo generar el cobro en PayPal."
    end
  end

  private

  def get_items_hash(orders)
    items = orders.map do |order|
      item = {}
      item[:name] = order.product.name
      item[:sku] = order.id.to_s
      item[:price] = order.price.to_s
      item[:currency] = 'USD'
      item[:quantity] = order.quantity
      item
    end
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :authenticate_user!

  def create
    p = Product.find(params[:product_id])
    o = Order.find_or_create_by(user: current_user, product: p, payed: false, price: p.price)
    o.quantity += 1

    if o.save
      redirect_to products_path, notice: "El producto ha sido agregado al carro."
    else
      redirect_to products_path, alert: "El producto NO ha sido agregado al carro"
    end
  end

  def clean
    @orders = Order.where(user: current_user, payed: false)
    @orders.destroy_all
    redirect_to orders_path, notice: 'El carro se ha vaciado.'
  end

  def index
    @orders = current_user.orders.cart
    @total = @orders.get_total
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Product.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/billings_helper.rb
module BillingsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/billings/index.html.erb
<div class="container">
  <% @billings.each do |billing| %>
    <p><%= billing.amount %></p>
    <hr>
    <% billing.orders.each do |order| %>
      <%= order.product.name %>
    <% end %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Carro2</title>
    <%= csrf_meta_tags %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css" integrity="sha384-/Y6pD6FV/Vv2HJnA6t+vslU6fwYXjCFtcEpHbNJ0lyAFsXTsjBbfaDjzALeQsN6M" crossorigin="anonymous">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <a class="navbar-brand" href="<%= root_path %>">Rails-Commerce</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link" href="<%= orders_path %>">Mi carro <span class="sr-only">(current)</span></a>
          </li>
        </ul>
        <ul class="navbar-nav ml-auto">
          
            <% if !user_signed_in? %>
              <li class="nav-item">
              <%= link_to 'Iniciar sesión', new_user_session_path, class: 'nav-link' %>
              </li>
              <li class="nav-item">
              <%= link_to 'Registrarse',  new_user_registration_path, class: 'nav-link'%>
              </li>
            <% else %>
            <li class="nav-item">
              <a class="nav-link"><%= current_user.name %></a>
            </li>
            <li class="nav-item">
              <%= link_to 'Cerrar sesión', destroy_user_session_path, method: :delete, class: 'nav-link' %>
            <% end %>
            </li>
            
        </ul>
      </div>
    </nav>

    <% if alert.present? %>
      <div class="alert alert-warning" role="alert">
        <%= alert %>
      </div>
    <% end %>

    <% if notice.present? %>
      <div class="alert alert-success" role="alert">
        <%= notice %>
      </div>
    <% end %>

    <div class="main-content">
      <%= yield %>
    </div>
  </body>
</html>

app/views/orders/create.html.erb
<h1>Orders#create</h1>
<p>Find me in app/views/orders/create.html.erb</p>

app/views/orders/index.html.erb
<div class="container">
  <% if @orders.count > 0 %>
    <table class="table">
    <thead>
      <tr>
        <th>Producto</th>
        <th>Valor</th>
        <th>Cantidad</th>
        <th>Subtotal</th>
      </tr>
    </thead>
    <tbody>
      <% @orders.each do |order| %>
        <tr>
          <td> <%= order.product.name %> </td>
          <td> <%= order.price %></td>
          <td> <%= order.quantity %> </td>
          <td> <%= order.price * order.quantity %></td>
        </tr>
      <% end %>
      <tr class="table-dark">
      <td></td>
      <td></td>
      <td><strong>Total de la compra:</strong></td>
      <td><strong><%= @total %></strong></td>
      </tr>
    </tbody>
  </table>

  <%= link_to 'Limpiar carro', clean_orders_path, class: 'btn btn-outline-danger'  %>

  <%= link_to 'Confirmar compra', pre_pay_billings_path, class: 'btn btn-success float-right' %>
  
  <% else %>
    <p>No tienes productos en tu carro de compra.</p>
  <% end %>

</div>

app/views/products/index.html.erb
<div class="container">
  <div class="row">
    <% @products.each_slice(4) do |row| %>
      <% row.each do |product| %>
        <div class="col">
          <div class="card">
            <%= image_tag product.photo, class: 'card-img-top' %>
            <div class="card-body">
              <h5> <%= product.name %> </h>
              <p> <%= product.price %> </p>
              <%= link_to "Agregar al carro", product_orders_path(product), class: 'btn btn-success', method: :post  %>
            </div>
          </div>
        </div>
      <% end %>
      <div class="w-100" style="margin-top:20px;"> </div>
    <% end %>
  </div>
</div>